name: Publish ecr

permissions:
  id-token: write
  contents: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: Define the version for the image
        required: true

jobs:
  login-to-ecr:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS creds via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::292095839402:role/oidc-github-actions-deployer
          aws-region: us-east-1
          mask-aws-account-id: 'false'
      - name: Login to ECR Docker
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
    outputs:
      registry: ${{ steps.login-ecr.outputs.registry }}
      docker_username: ${{ steps.login-ecr.outputs.docker_username_292095839402_dkr_ecr_us_east_1_amazonaws_com }}
      docker_password: ${{ steps.login-ecr.outputs.docker_password_292095839402_dkr_ecr_us_east_1_amazonaws_com }}
  ecr-build:
    runs-on: ubuntu-latest # Corrected the spelling of 'ubuntu-latest'
    needs: login-to-ecr
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Publish image
        env:
          ECR_REGISTRY: ${{ needs.login-to-ecr.outputs.registry }}
          ECR_REPOSITORY: fetchrewards/bark-api
          IMAGE_TAG: ${{ inputs.version }}
        run: |
          aws ecr create-repository --repository-name $ECR_REPOSITORY || true
          docker buildx build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --platform=linux/amd64 --build-arg GO_PROXY=$GOPROXY .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      - name: Logout of Amazon ECR
        if: always()
        run: docker logout ${{ steps.login-ecr.outputs.registry }}
